// Generated by `npm run rooms` – the painted room states (still + animation strip), bundled as data URLs.
import room_arkan from "./arkan.png";
import room_arkan_anim from "./arkan-anim.png";
import room_brand from "./brand.png";
import room_brand_anim from "./brand-anim.png";
import room_einsturz from "./einsturz.png";
import room_einsturz_anim from "./einsturz-anim.png";
import room_eis from "./eis.png";
import room_eis_anim from "./eis-anim.png";
import room_finster from "./finster.png";
import room_finster_anim from "./finster-anim.png";
import room_flut from "./flut.png";
import room_flut_anim from "./flut-anim.png";
import room_funken from "./funken.png";
import room_funken_anim from "./funken-anim.png";
import room_gift from "./gift.png";
import room_gift_anim from "./gift-anim.png";
import room_gruft from "./gruft.png";
import room_gruft_anim from "./gruft-anim.png";
import room_heilig from "./heilig.png";
import room_heilig_anim from "./heilig-anim.png";
import room_nebel from "./nebel.png";
import room_nebel_anim from "./nebel-anim.png";
import room_sturm from "./sturm.png";
import room_sturm_anim from "./sturm-anim.png";
import room_traum from "./traum.png";
import room_traum_anim from "./traum-anim.png";
import room_wald from "./wald.png";
import room_wald_anim from "./wald-anim.png";

export const ROOM_PICTURES: Readonly<Record<string, string>> = {
  "arkan": room_arkan,
  "arkan-anim": room_arkan_anim,
  "brand": room_brand,
  "brand-anim": room_brand_anim,
  "einsturz": room_einsturz,
  "einsturz-anim": room_einsturz_anim,
  "eis": room_eis,
  "eis-anim": room_eis_anim,
  "finster": room_finster,
  "finster-anim": room_finster_anim,
  "flut": room_flut,
  "flut-anim": room_flut_anim,
  "funken": room_funken,
  "funken-anim": room_funken_anim,
  "gift": room_gift,
  "gift-anim": room_gift_anim,
  "gruft": room_gruft,
  "gruft-anim": room_gruft_anim,
  "heilig": room_heilig,
  "heilig-anim": room_heilig_anim,
  "nebel": room_nebel,
  "nebel-anim": room_nebel_anim,
  "sturm": room_sturm,
  "sturm-anim": room_sturm_anim,
  "traum": room_traum,
  "traum-anim": room_traum_anim,
  "wald": room_wald,
  "wald-anim": room_wald_anim,
};
