// Generated by `npm run rooms` – the painted room states (still + animation strip), bundled as data URLs.
import room_brand from "./brand.png";
import room_einsturz from "./einsturz.png";
import room_eis from "./eis.png";
import room_eis_anim from "./eis-anim.png";
import room_finster from "./finster.png";
import room_finster_anim from "./finster-anim.png";
import room_flut from "./flut.png";
import room_flut_anim from "./flut-anim.png";
import room_nebel from "./nebel.png";
import room_sturm from "./sturm.png";

export const ROOM_PICTURES: Readonly<Record<string, string>> = {
  "brand": room_brand,
  "einsturz": room_einsturz,
  "eis": room_eis,
  "eis-anim": room_eis_anim,
  "finster": room_finster,
  "finster-anim": room_finster_anim,
  "flut": room_flut,
  "flut-anim": room_flut_anim,
  "nebel": room_nebel,
  "sturm": room_sturm,
};
