// Generated by `npm run effects` – the painted attack animations, bundled as data URLs.
import fx_acid from "./acid.png";
import fx_acid_impact from "./acid-impact.png";
import fx_arcane from "./arcane.png";
import fx_arcane_impact from "./arcane-impact.png";
import fx_arrow from "./arrow.png";
import fx_arrow_impact from "./arrow-impact.png";
import fx_bite from "./bite.png";
import fx_bullet from "./bullet.png";
import fx_bullet_impact from "./bullet-impact.png";
import fx_chains from "./chains.png";
import fx_claws from "./claws.png";
import fx_crush from "./crush.png";
import fx_drain from "./drain.png";
import fx_explosion from "./explosion.png";
import fx_explosion_impact from "./explosion-impact.png";
import fx_fireball from "./fireball.png";
import fx_fireball_impact from "./fireball-impact.png";
import fx_hearts from "./hearts.png";
import fx_hearts_impact from "./hearts-impact.png";
import fx_holy from "./holy.png";
import fx_ice from "./ice.png";
import fx_ice_impact from "./ice-impact.png";
import fx_lightning from "./lightning.png";
import fx_mind from "./mind.png";
import fx_mind_impact from "./mind-impact.png";
import fx_paper from "./paper.png";
import fx_paper_impact from "./paper-impact.png";
import fx_petrify from "./petrify.png";
import fx_pierce from "./pierce.png";
import fx_poison from "./poison.png";
import fx_poison_impact from "./poison-impact.png";
import fx_shadow from "./shadow.png";
import fx_slash from "./slash.png";
import fx_sleep from "./sleep.png";
import fx_sleep_impact from "./sleep-impact.png";
import fx_sound from "./sound.png";
import fx_sound_impact from "./sound-impact.png";
import fx_tornado from "./tornado.png";
import fx_void from "./void.png";
import fx_wave from "./wave.png";

export const EFFECT_SHEETS: Readonly<Record<string, string>> = {
  "acid": fx_acid,
  "acid-impact": fx_acid_impact,
  "arcane": fx_arcane,
  "arcane-impact": fx_arcane_impact,
  "arrow": fx_arrow,
  "arrow-impact": fx_arrow_impact,
  "bite": fx_bite,
  "bullet": fx_bullet,
  "bullet-impact": fx_bullet_impact,
  "chains": fx_chains,
  "claws": fx_claws,
  "crush": fx_crush,
  "drain": fx_drain,
  "explosion": fx_explosion,
  "explosion-impact": fx_explosion_impact,
  "fireball": fx_fireball,
  "fireball-impact": fx_fireball_impact,
  "hearts": fx_hearts,
  "hearts-impact": fx_hearts_impact,
  "holy": fx_holy,
  "ice": fx_ice,
  "ice-impact": fx_ice_impact,
  "lightning": fx_lightning,
  "mind": fx_mind,
  "mind-impact": fx_mind_impact,
  "paper": fx_paper,
  "paper-impact": fx_paper_impact,
  "petrify": fx_petrify,
  "pierce": fx_pierce,
  "poison": fx_poison,
  "poison-impact": fx_poison_impact,
  "shadow": fx_shadow,
  "slash": fx_slash,
  "sleep": fx_sleep,
  "sleep-impact": fx_sleep_impact,
  "sound": fx_sound,
  "sound-impact": fx_sound_impact,
  "tornado": fx_tornado,
  "void": fx_void,
  "wave": fx_wave,
};
