// Generated by `npm run effects` – the painted attack animations, bundled as data URLs.
import fx_fireball from "./fireball.png";
import fx_fireball_impact from "./fireball-impact.png";
import fx_slash from "./slash.png";

export const EFFECT_SHEETS: Readonly<Record<string, string>> = {
  "fireball": fx_fireball,
  "fireball-impact": fx_fireball_impact,
  "slash": fx_slash,
};
