// Generated by `npm run effects` – the painted attack animations, bundled as data URLs.
import fx_arrow from "./arrow.png";
import fx_bullet from "./bullet.png";
import fx_bullet_impact from "./bullet-impact.png";
import fx_explosion from "./explosion.png";
import fx_explosion_impact from "./explosion-impact.png";
import fx_fireball from "./fireball.png";
import fx_fireball_impact from "./fireball-impact.png";
import fx_slash from "./slash.png";

export const EFFECT_SHEETS: Readonly<Record<string, string>> = {
  "arrow": fx_arrow,
  "bullet": fx_bullet,
  "bullet-impact": fx_bullet_impact,
  "explosion": fx_explosion,
  "explosion-impact": fx_explosion_impact,
  "fireball": fx_fireball,
  "fireball-impact": fx_fireball_impact,
  "slash": fx_slash,
};
